### ISSUE TITLE
CStr::from_ptr length too short by one

### ISSUE THREAD

**Issue by haraldh** [arcnmx/cstrptr-rs#4]
https://github.com/arcnmx/cstrptr-rs/blob/bdc51fcaf3892fc26135f44cf04749eed9d5125c/src/cstr.rs#L30-L33

this should probably be:
```rust
Self::from_bytes_with_nul_unchecked(core::slice::from_raw_parts(ptr as *const _, len + 1))
```

**Comment by arcnmx** [comment]
Ouch, sorry about that and thanks for catching it!
